global using Moq;
global using MediatR;
global using NUnit.Framework;
global using System.Threading;
global using PetClinic.Interfaces;
global using PetClinic.Infrastructure;
global using PetClinic.Domain.Entities;
global using Microsoft.EntityFrameworkCore;
global using PetClinic.Application.Exceptions;
global using PetClinic.Application.Interfaces;
global using PetClinic.Infrastructure.Repository;
global using PetClinic.Application.Owners.Queries.Get;
global using PetClinic.Application.Owners.Commands.Create;
global using PetClinic.Application.Owners.Commands.Delete;
global using PetClinic.Application.Owners.Commands.Update;
global using CreateDoctors = PetClinic.Application.Doctors.Commands.Create;
global using UpdateDoctors = PetClinic.Application.Doctors.Commands.Update;
global using DeleteDoctors = PetClinic.Application.Doctors.Commands.Delete;
global using GetDoctors = PetClinic.Application.Doctors.Queries.Get;