// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetCare.Infrastructure;

#nullable disable

namespace PetCare.Infrastructure.Migrations
{
    [DbContext(typeof(PetCareDbContext))]
    [Migration("20230113150004_SeedingDataInSchedulesTable")]
    partial class SeedingDataInSchedulesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PetCare.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("ImageFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartedJobDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 33,
                            FirstName = "Gergana",
                            ImageFilePath = "C:\\Simeon\\Programming\\Amdaris\\Assignemnts-Git-Repo\\PetCareApp\\PetCare-FE\\public\\img\\the-team\\team-3.jpg",
                            IsDeleted = false,
                            JobDescription = "Emergency medical care, internal medicine",
                            LastName = "Nikolova",
                            Phonenumber = "0245003",
                            StartedJobDate = new DateTime(2018, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Age = 26,
                            FirstName = "Valentina",
                            ImageFilePath = "C:\\Simeon\\Programming\\Amdaris\\Assignemnts-Git-Repo\\PetCareApp\\PetCare-FE\\public\\img\\the-team\\team-4.jpg",
                            IsDeleted = false,
                            JobDescription = "Parasitology and infectious diseases",
                            LastName = "Naidenova",
                            Phonenumber = "0213168",
                            StartedJobDate = new DateTime(2018, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Age = 46,
                            FirstName = "Borislava",
                            ImageFilePath = "C:\\Simeon\\Programming\\Amdaris\\Assignemnts-Git-Repo\\PetCareApp\\PetCare-FE\\public\\img\\the-team\\team-5.jpg",
                            IsDeleted = false,
                            JobDescription = "orthopedics and traumatology, abdominal and thoracic surgery, panelist",
                            LastName = "Georgieva",
                            Phonenumber = "0211853",
                            StartedJobDate = new DateTime(2011, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Age = 35,
                            FirstName = "Veselin",
                            ImageFilePath = "C:\\Simeon\\Programming\\Amdaris\\Assignemnts-Git-Repo\\PetCareApp\\PetCare-FE\\public\\img\\the-team\\team-6.jpg",
                            IsDeleted = false,
                            JobDescription = "exotic animals, internal diseases",
                            LastName = "Milushev",
                            Phonenumber = "0236578",
                            StartedJobDate = new DateTime(2010, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Age = 26,
                            FirstName = "Petko",
                            ImageFilePath = "C:\\Simeon\\Programming\\Amdaris\\Assignemnts-Git-Repo\\PetCareApp\\PetCare-FE\\public\\img\\the-team\\team-7.jpg",
                            IsDeleted = false,
                            JobDescription = "Emergency medical, internal medicine and infectious diseases.",
                            LastName = "Stanimiraov",
                            Phonenumber = "0241598",
                            StartedJobDate = new DateTime(2011, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Age = 31,
                            FirstName = "Ivan",
                            ImageFilePath = "C:\\Simeon\\Programming\\Amdaris\\Assignemnts-Git-Repo\\PetCareApp\\PetCare-FE\\public\\img\\the-team\\team-8.jpg",
                            IsDeleted = false,
                            JobDescription = "Cardiology, thoracic surgery, has interests in dentistry.",
                            LastName = "Petrov",
                            Phonenumber = "087458589",
                            StartedJobDate = new DateTime(2013, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceptionistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ReceptionistId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            FirstName = "Stanimir",
                            IsDeleted = false,
                            LastName = "Petkov",
                            Phonenumber = "0888399827"
                        },
                        new
                        {
                            Id = 2,
                            Age = 30,
                            FirstName = "Desislava",
                            IsDeleted = false,
                            LastName = "Koleva",
                            Phonenumber = "0897247597"
                        },
                        new
                        {
                            Id = 3,
                            Age = 43,
                            FirstName = "Vencislav",
                            IsDeleted = false,
                            LastName = "Kolev",
                            Phonenumber = "0884156471"
                        },
                        new
                        {
                            Id = 4,
                            Age = 26,
                            FirstName = "Simeon",
                            IsDeleted = false,
                            LastName = "Kostadinov",
                            Phonenumber = "0880368788"
                        });
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("ImageFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceptionistId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ReceptionistId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            Breed = "Akita",
                            IsDeleted = false,
                            Name = "Bella",
                            OwnerId = 4,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 2,
                            Age = 4,
                            Breed = "Street",
                            IsDeleted = false,
                            Name = "Milo",
                            OwnerId = 4,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 3,
                            Age = 1,
                            Breed = "Syrian",
                            IsDeleted = false,
                            Name = "Loki",
                            OwnerId = 1,
                            Type = "Hamster"
                        },
                        new
                        {
                            Id = 4,
                            Age = 1,
                            Breed = "Bichon Frise",
                            IsDeleted = false,
                            Name = "Simba",
                            OwnerId = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 5,
                            Age = 1,
                            Breed = "Street",
                            IsDeleted = false,
                            Name = "Nala",
                            OwnerId = 3,
                            Type = "Cat"
                        });
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Receptionist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("ImageFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartedJobDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Receptionists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 24,
                            FirstName = "Katya",
                            IsDeleted = false,
                            JobDescription = "Receptionist",
                            LastName = "Manolova",
                            Phonenumber = "0239949",
                            StartedJobDate = new DateTime(2018, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Age = 35,
                            FirstName = "Tanyq",
                            IsDeleted = false,
                            JobDescription = "Receptionist",
                            LastName = "Gramatikova",
                            Phonenumber = "0239949",
                            StartedJobDate = new DateTime(2018, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Age = 24,
                            FirstName = "Vesela",
                            IsDeleted = false,
                            JobDescription = "Receptionist",
                            LastName = "Cvetkova",
                            Phonenumber = "0239949",
                            StartedJobDate = new DateTime(2018, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2023, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2023, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2023, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2023, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2023, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2023, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2023, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 1,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2023, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2023, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2023, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2023, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2023, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2023, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2023, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 2,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2023, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2023, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2023, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2023, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2023, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTime(2023, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTime(2023, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 3,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 58,
                            Date = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 59,
                            Date = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 60,
                            Date = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 61,
                            Date = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 62,
                            Date = new DateTime(2023, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 63,
                            Date = new DateTime(2023, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 64,
                            Date = new DateTime(2023, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 65,
                            Date = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 66,
                            Date = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 67,
                            Date = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 68,
                            Date = new DateTime(2023, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 69,
                            Date = new DateTime(2023, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 70,
                            Date = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 71,
                            Date = new DateTime(2023, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 72,
                            Date = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 73,
                            Date = new DateTime(2023, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 74,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 75,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 76,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 4,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 77,
                            Date = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 78,
                            Date = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 79,
                            Date = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 80,
                            Date = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 81,
                            Date = new DateTime(2023, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 82,
                            Date = new DateTime(2023, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 83,
                            Date = new DateTime(2023, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 84,
                            Date = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 85,
                            Date = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 86,
                            Date = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 87,
                            Date = new DateTime(2023, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 88,
                            Date = new DateTime(2023, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 89,
                            Date = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 90,
                            Date = new DateTime(2023, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 91,
                            Date = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 92,
                            Date = new DateTime(2023, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 93,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 94,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 95,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 5,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 96,
                            Date = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 97,
                            Date = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 98,
                            Date = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 99,
                            Date = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 100,
                            Date = new DateTime(2023, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 101,
                            Date = new DateTime(2023, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 102,
                            Date = new DateTime(2023, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 103,
                            Date = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 104,
                            Date = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 105,
                            Date = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 106,
                            Date = new DateTime(2023, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 107,
                            Date = new DateTime(2023, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 108,
                            Date = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 109,
                            Date = new DateTime(2023, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 110,
                            Date = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 111,
                            Date = new DateTime(2023, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = true
                        },
                        new
                        {
                            Id = 112,
                            Date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 113,
                            Date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = false
                        },
                        new
                        {
                            Id = 114,
                            Date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = 6,
                            IsAvailable = true
                        });
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Owner", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Doctor", "Doctor")
                        .WithMany("OwnersOfPatients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetCare.Domain.Entities.Receptionist", "Receptionist")
                        .WithMany("OwnersOfPatients")
                        .HasForeignKey("ReceptionistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Doctor");

                    b.Navigation("Receptionist");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetCare.Domain.Entities.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.Domain.Entities.Receptionist", "Receptionist")
                        .WithMany("Patients")
                        .HasForeignKey("ReceptionistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Doctor");

                    b.Navigation("Owner");

                    b.Navigation("Receptionist");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Schedule")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("OwnersOfPatients");

                    b.Navigation("Patients");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Owner", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Receptionist", b =>
                {
                    b.Navigation("OwnersOfPatients");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
